name: Dice Roller Compose Stack

services:
  api-2:
    # image: mysupercooldiceroller:latest-${NODE_ENV:-production}
    build:
      context: .
      args:
        - NODE_ENV:bananas
    env_file: .env
    environment:
      - SOMEOTHERENVVARIABLE=SOMEVALUEHERE
      - ANOTHERENVVARIABLE=BANANAS
    ports:
      - "127.0.0.1:3500:3000"