apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mar25-express-dice-api-cluster
  labels:
    app: mar25-express-dice-api-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mar25-express-dice-api-cluster
  template:
    metadata:
      labels:
        app: mar25-express-dice-api-cluster
    spec:
      containers:
        - name: mar25-express-dice-api-container
          image: ghcr.io/alexstormwood/express-dice-api:latest
          ports:
          - containerPort: 3500
          env:
          - name: JWT_SECRET_KEY
            value: blahblahblahblah 
          - name: DATABASE_URL
            value: some-mongodb-connection-string-here