name: Deploy to GCP 

on:
  workflow_run:
    workflows: [Build and push Docker image to GHCR]
    types:
      - completed
  workflow_dispatch:

jobs:
  gcp-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GPC_CREDENTIALS }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          service: 'express-dice-api'
          image: 'ghcr.io/alexstormwood/express-dice-api:latest'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
