name: Build and push Docker image to GHCR 

on:
  push:
    tags: ["v*"]

  workflow_dispatch:
    inputs:
      new-version-tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    # environment variables for docker image metadata
    env:
      OWNER_LC: ""
      REPO_LC: ""
      VERSION_TAG: ""

    permissions:
      packages: write
      contents: read

    steps:

      # # From Jordan!
      # - name: Create Image Tags
      #   id: create_tags
      #   run: |
      #     if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
      #       TAG="${GITHUB_REF#refs/tags/v}-${GITHUB_SHA::7}"
      #     else
      #       LATEST_TAG=$(git tag --sort=-version:refname | head -1 | sed 's/^v//')
      #       TAG="${LATEST_TAG}-manual-${GITHUB_SHA::7}"
      #     fi
      #     echo "tag=${TAG}" >> $GITHUB_OUTPUT
      #     echo "Created image tag: ${TAG}"
      #     echo "${TAG}" > tag.txt

      - name: Get the image version tag from either dispatch or ref
        run: |
          echo "VERSION_TAG=${ACTIVE_TAG,,}" >>${GITHUB_ENV}
        env:
          ACTIVE_TAG: '${{ github.ref_name || inputs.new-version-tag }}'

      - name: Sanitise env data for Docker image tagging
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          echo "REPO_LC=${REPO,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          REPO: '${{ github.repository }}'
          
      # Log in to our target container registry
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Additional helper for multi-platform image builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Another additional helper for multi-platform image builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Actual image building and image pushing
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{env.REPO_LC}}:latest
            ghcr.io/${{env.REPO_LC}}:${{env.VERSION_TAG}}